### ISSUE TITLE
Navigation(导航栏)重新render后Item的selected状态没有重置

### ISSUE THREAD

**Issue by yingxiaoqiang** [INTL-Alibaba/qnui#11]
![image](https://cloud.githubusercontent.com/assets/16712872/23118490/51b426b4-f78f-11e6-8aaf-feca1bebdb4d.png)
如上图，我们点击设置图标的时候需要打开一个新页面，想把当前菜单的选中样式给去掉。现在的做法是点击设置的时候重新render导航栏，但是Training菜单的选中状态不会消失，下面的问题重现的在线演示：
http://codepen.io/anon/pen/wgLqEO?editors=0011

**Comment by fattydevelop** [comment]
![image](https://cloud.githubusercontent.com/assets/3349721/23204549/fd67a6be-f921-11e6-80ff-beb1f3683b8f.png)

navigation在item上提供了一个`selectedStyle` API，可以通过在点击设置后重置`selectedStyle`为`false`实现其他选中条的非选中状态。

API具体使用方式可以参考 `http://qnui.taobao.org/docs/navigation/?type=Navigation`

**Comment by yingxiaoqiang** [comment]
不起作用的，selectedStyle=false只是阻止了其他Item点击时变成选中状态，但是并不会让已变成选中状态的Item变成非选中状态

**Comment by yingxiaoqiang** [comment]
解决办法，使用selectedKey做受控处理：
http://codepen.io/anon/pen/wgLqEO?editors=0001
