### ISSUE TITLE
qnui内部组件全部使用cdn,有没有相关示例

### ISSUE THREAD

**Issue by stone1235** [INTL-Alibaba/qnui#12]
所有都用qnui组件，按需加载导致每个文件都挺大的，有没有全局引入https://g.alicdn.com/qn/QNUI-OPEN//0.1.9/qnui.min.js，组件的使用示例。

**Comment by fattydevelop** [comment]
目前还没有这个demo，稍后我可以在文档中补充使用方法。大致方案如下，你可以先行尝试一下：
- 在页面挂载的index.html中，引用CDN资源(在业务代码前)
- webpack.config.js 中设置external qnui，防止重复打包qnui。

具体demo写好后，我会在此处同步该信息，还请关注。

**Comment by fattydevelop** [comment]
**^0.3.x**以上版本中，qnui已经提供了引用CDN方式的脚手架，使用文档可以参考  [https://github.com/fieteam/fie-toolkit-qnui](https://github.com/fieteam/fie-toolkit-qnui)
