### ISSUE TITLE
上传组件可否增加一个控制上传的Api，而不是选中一个文件就直接上传了

### ISSUE THREAD

**Issue by flyoverGu** [INTL-Alibaba/qnui#15]

**Comment by fattydevelop** [comment]
`beforeUpload`  看下这个API是否满足你的需求

![test](https://img.alicdn.com/tfs/TB13e25PVXXXXbcapXXXXXXXXXX-1180-254.png)

**Comment by flyoverGu** [comment]
不能满足我的需求。 我的需求是用户先选中了一个文件，然后点击确定再上传。 用beforeUpload只能阻止上传，没法再控制文件继续上传。

**Comment by fattydevelop** [comment]
和组件作者讨论了一下，目前还无法支持你的使用场景
