### ISSUE TITLE
如何使用Icon组件，定义自己的图标？

### ISSUE THREAD

**Issue by g770728y** [INTL-Alibaba/qnui#16]
## 1. Navigation.Item里，需要引入新的icon。文档建议改icon属性，因此尝试这样做：

    let qnui-icon = **<Icon type="set"></i>**
    <Item key="admin" text="用户管理" icon={admin-icon}></Item>

  显示没有问题。但icon不是我想要的，所以继续第2步。

## 2. 换成自己的icon：

    let admin-icon = **<i class-name="iconfont admin-icon"></i>**  
    <Item key="admin" text="用户管理" icon={admin-icon}></Item>

    
结果错误，icon没有显示，console没有报错。
这表明Navigation.Item的icon属性，只支持<Icon>组件。

## 3. 貌似Icon组件的图标完全是固定的？
查文档：

    <Icon type="email" />

将渲染为：

    <i class="next-icon next-icon-${type}"></i>
 
查css文件：

    .next-icon {
        font-family:NextIcon;  
       ...}
    @font-face {
        font-family:NextIcon;
        ...
    }

这种方式，貌似无法加入自己的图标了。

## 4. 请教：
4.1 有什么办法加入自己的图标吗？
4.2 如果Icon组件的图标一定要固定，那么有什么办法在Navigation.Item里加入自定义图标？
谢过先

**Comment by fattydevelop** [comment]
1、目前ICON组件还没有办法加入自定义图标
2、如果要在Navigation中自定义icon，可以通过引入的content API进行设置，详情见http://codepen.io/doub/pen/PppQLd/?editors=0110
```
<Item content = {<a href="somewhere">
      <i className="custom-icon">&#xe602;</i> 
<span>33333</span></a>}>
```

**Comment by g770728y** [comment]
多谢：）
