### ISSUE TITLE
Tab里怎么在设置content显示一个表格或者html

### ISSUE THREAD

**Issue by dahuzix** [INTL-Alibaba/qnui#17]
const data = [{
    key: 1,
    name: 'a',
    age: 32,
    address: '我是a',
    children: [{
        key: 11,
        name: 'aa',
        age: 33,
        address: '我是aa',
    }, {
        key: 12,
        name: 'ab',
        age: 33,
        address: '我是ab',
        children: [{
            key: 121,
            name: 'aba',
            age: 33,
            address: '我是aba',
        }],
    }, {
        key: 13,
        name: 'ac',
        age: 33,
        address: '我是ac',
        children: [{
            key: 131,
            name: 'aca',
            age: 33,
            address: '我是aca',
            children: [{
                key: 1311,
                name: 'acaa',
                age: 33,
                address: '我是acaa',
            }, {
                key: 1312,
                name: 'acab',
                age: 33,
                address: '我是acab',
            }],
        }],
    }],
}, {
    key: 2,
    name: 'b',
    age: 32,
    address: '我是b',
    children: []
}];
const tableMixExpanded = <Table dataSource={data}
                                primaryKey="key"
                                expandedRowRender = {(record)=> record.address}
                                rowSelection={{onChange: () => {}}}>
    <Table.Column title="Key" dataIndex="key"/>
    <Table.Column title="Name" dataIndex="name"/>
    <Table.Column title="Age" dataIndex="age" />
    <Table.Column title="Address" dataIndex="address"/>
</Table>
const TabPane = Tab.TabPane;

const tabs = [
    { tab: '首页', key: 0, content: {tableMixExpanded} },
    { tab: '文档', key: 1, content: '' },
    { tab: 'API', key: 2, content: '' },
]

这样写报错啊

**Comment by fattydevelop** [comment]
tab的content API可以用于盛放自定义字段
```
const tabs = [
    { tab: '首页', key: 0, content: <Table dataSource={getData()}
                       rowSelection={rowSelection}>
    <Table.Column title="Id" dataIndex="id"/>
    <Table.Column title="Title" dataIndex="title.name"/>
    <Table.Column title="Time" dataIndex="time"/>
    <Table.Column cell={render} width={200}/>
</Table> },
    { tab: '文档', key: 1, content: '这里是文档内容' },
    { tab: 'API', key: 2, content: '这里是 API 内容' },
];
```
具体demo见 http://codepen.io/doub/pen/EWXxrv?editors=1010
