### ISSUE TITLE
select option 里写<i>自定义icon 不显示

### ISSUE THREAD

**Issue by dahuzix** [INTL-Alibaba/qnui#18]
select option 里写<i>自定义icon 不显示
js：
`            <Select className="search-bar-query"
                                    {...init('remark', {initValue: '全部'})}
                                >
                                    <Option  value="0">全部</Option >
                                    <Option  value="1"><i className="icon-square mark-orange"></i>标记</Option >
                                    <Option  value="2">2</Option >
                                    <Option  value="3">3</Option >
                                    <Option  value="4">4</Option >
                                    <Option  value="5">5</Option >
                                </Select>`
css：            
.icon-square{
  width: 20px;
  height: 20px;
}
.mark-orange{
  color: orangered;
  background-color: orangered;
}

**Comment by fattydevelop** [comment]
1、如果是dataSource渲染可以使用下图的这个demo，在qnui.taobao.org中有这个富文本渲染的例子
![img](https://img.alicdn.com/tfs/TB1yMgQPVXXXXahapXXXXXXXXXX-739-632.png)
2、如果只是普通的Option平铺可以参考这个demo  http://codepen.io/doub/pen/GWEWNb
![img](https://img.alicdn.com/tfs/TB1M4k_PVXXXXcFXFXXXXXXXXXX-409-275.png)
自定义icon和qnui ICON都是支持的
