### ISSUE TITLE
table 怎么配置能实现展开/合上全部

### ISSUE THREAD

**Issue by dahuzix** [INTL-Alibaba/qnui#19]
table 怎么配置能实现展开/合上全部？通过配置hasExpandedRowCtrl = {true} 不起作用
就跟全选和取消类似的，现在只能一个一个展开每一行？
![qq 20170314172742](https://cloud.githubusercontent.com/assets/7640220/23894193/22dee9ce-08dc-11e7-91f4-32037716b4d1.png)

**Comment by fattydevelop** [comment]
不支持最上面的红色加号，不过你可以通过`openRowKeys `这个API使得表格展开受控，控制展开的项目列表。

**Comment by fattydevelop** [comment]
如果不是tree模式可以通过`expandedRowKeys`这个API实现，这里有个相关的demo可以参考http://codepen.io/doub/pen/VpzEMZ?editors=0010
