### ISSUE TITLE
qnui项目脚手架

### ISSUE THREAD

**Issue by fattydevelop** [INTL-Alibaba/qnui#2]
### 目前还没有统一的项目脚手架，暂时使用yomen **generator-react-webpack**替代。

- 用户可以参考demo目录中的todoMVC作为起始项目

- redux、router等具体demo待补充

**Comment by penggangg** [comment]
您好，我想问一下，index页面引入的assets/app.js是入口js文件吗？起到所有的js都需要在它里面引的功能吗？我想新开一个页面，然后也想引入同样的样式，请问要怎么才能实现呢？

**Comment by fattydevelop** [comment]
assets/app.js是你的业务逻辑代码，在逻辑代码前引入qnui的cdn代码，并在webpack的external中配置qnui=Next即可

**Comment by fattydevelop** [comment]
@penggangg 下周会提供一个cdn使用的demo，并提供最佳实践脚手架
