### ISSUE TITLE
[bug] from qnui3.0 qnui/lib/date-picker

### ISSUE THREAD

**Issue by filefoxper** [INTL-Alibaba/qnui#21]
通过React.Children.map()的形式生成Component中使用了date-picker,并开启了showTime属性。

在使用date-picker中的时间控件时报异常，但不影响操作。

异常点：

Gateway.prototype.componentWillReceiveProps = function componentWillReceiveProps(newProps) {
        if (this.wrapper && newProps.container !== this.props.container) {
            this.getContainerNode(newProps).appendChild(this.wrapper);
        }
    };

原因this.getContainerNode(newProps)结果为undefined

异常如下：

Uncaught TypeError: Cannot read property 'appendChild' of null
    at Gateway.componentWillReceiveProps (gateway.js:48)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:614)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:754)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:645)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:754)
componentWillReceiveProps @ gateway.js:48
updateComponent @ ReactCompositeComponent.js:614
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
performUpdateIfNecessary @ ReactCompositeComponent.js:559
performUpdateIfNecessary @ ReactReconciler.js:157
runBatchedUpdates @ ReactUpdates.js:150
perform @ Transaction.js:140
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
close @ ReactUpdates.js:47
closeAll @ Transaction.js:206
perform @ Transaction.js:153
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
close @ ReactUpdates.js:47
closeAll @ Transaction.js:206
perform @ Transaction.js:153
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
close @ ReactUpdates.js:47
closeAll @ Transaction.js:206
perform @ Transaction.js:153
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147

**Comment by fattydevelop** [comment]
你好  @可否提供在codepen中提供一个问题demo，帮助我快速定位问题，多谢
http://codepen.io/doub/pen/rWZeJN

**Comment by filefoxper** [comment]
你好，在你们的codepen上的运行结果是正常的......

**Comment by fattydevelop** [comment]
@filefoxper  codepen上使用的是目前最新版本0.3.1。可能是0.3.0的一个bug

**Comment by fattydevelop** [comment]
暂时关闭，如有问题，将重新打开
