### ISSUE TITLE
Table组件控制内部自动生成div的padding样式

### ISSUE THREAD

**Issue by yingxiaoqiang** [INTL-Alibaba/qnui#22]
Table组件里面自动生成的div，padding: 12px 16px;这个样式太大了，是否有自定义控制的方法

**Comment by fattydevelop** [comment]
目前还没有控制padding的API，如果确实需要可以通过覆盖样式，或重写node_modules中的scss变量实现[文档](http://qnui.taobao.org/start/variables/?type=%E5%8F%98%E9%87%8F%E9%85%8D%E7%BD%AE)。

**Comment by yingxiaoqiang** [comment]
scss变量没有支持，通过覆盖样式解决了，谢谢
