### ISSUE TITLE
Input组件的defaultValue第二次render不起作用

### ISSUE THREAD

**Issue by yingxiaoqiang** [INTL-Alibaba/qnui#25]
Input组件的defaultValue初始化值，第一次render的时候起作用的，在componentDidMount或者通过其他方式重置，第二次render的时候就不起作用了，value参数可以起作用，但是又禁止编辑，请问有什么办法解决？
在线重现演示：
http://codepen.io/anon/pen/vxjJPX?editors=0011

**Comment by fattydevelop** [comment]
这个是组件的受限使用与非受限使用的区别
![image](https://cloud.githubusercontent.com/assets/3349721/24230094/2c9a2f86-0fb8-11e7-9ceb-50a3a0c782d6.png)

两种用法各有差别，可以参考https://itbilu.com/javascript/react/4ki9qFFqg.html这篇文章里提到的概念。
