### ISSUE TITLE
时间选择器bug   希望处理

### ISSUE THREAD

**Issue by toyanghong** [INTL-Alibaba/qnui#3]
选择时间后 无法自动关闭弹出，您可以试试官方demo

**Comment by fattydevelop** [comment]
应该是失去焦点的事件没有捕捉到，含有弹窗的组件目前均有该问题，此问题会尽快修复。

**Comment by fattydevelop** [comment]
已在0.1.8版本修复，如果依然存在该问题，我将重新打开该issue。
