### ISSUE TITLE
qnui没有components文件夹

### ISSUE THREAD

**Issue by GoToBoy** [INTL-Alibaba/qnui#30]
- qnui 版本: 1.11
- 操作系统及其版本: mac os 10.12.13
- 浏览器及其版本: chrome

操作流程：
clone todoMVC-demo 项目，依照readme提示npm install、npm start , 运行后涉及到qnui包的组件报不存在错误，打开node_modules下qnui文件夹里面没有lib、components文件夹，是否已经关闭这个项目了？

**Comment by fattydevelop** [comment]
麻烦升级已下qnui版本，demo中的例子比较老了。可以使用fie-toolkit-qnui脚手架用作qnui的项目开发。文档地址 https://github.com/fieteam/fie-toolkit-qnui
