### ISSUE TITLE
Tag组件显示动画需求

### ISSUE THREAD

**Issue by mx560** [INTL-Alibaba/qnui#31]
Tag组件的动画效果希望可以做成可配置的（有无动画效果），有的时候不需要动画效果，比如包装成可拖动标签时，在鼠标没释放前，Tag会不停的闪烁

**Comment by bindoon** [comment]
@fattydevelop 能给个截图不看看是如何操作闪烁的

**Comment by fattydevelop** [comment]
@qiaogeng-hub    麻烦提供一下复现路径或者是操作截图或GIF   http://codepen.io/doub/pen/rWZeJN

**Comment by mx560** [comment]
![tag](https://cloud.githubusercontent.com/assets/1431013/26230702/73e9aa28-3c7d-11e7-843b-f2eed62c16f3.gif)

**Comment by fattydevelop** [comment]
0.5.0已支持
