### ISSUE TITLE
input  设置 value 受控后，使用 Field.validate, 会清空input 的值，并验证报错

### ISSUE THREAD

**Issue by dahuzix** [INTL-Alibaba/qnui#39]
input  设置 value 受控后，使用 Field.validate, 会清空value 的指，并验证报错，

不要手动输入，直接修改input  中 value 的值

具体 在 code pen 中测试代码

const { DatePicker,Form,Field,Input,Button } = qnui;

class Test extends React.Component{
      constructor(props) {
        super(props);
        this.field = new Field(this);
      }
  
  
      save(e){
        e.preventDefault();
        this.field.validate((errors, values) => {
            console.log('values',values);
            
        });
      }
  
       render(){
               const {init} = this.field;
  
         return(
          <div>
                 <Form field={this.field}>
                   
                           <Input maxLength={30} 
                             hasLimitHint 
                             placeholder="公司名称"
                               value='点击保存验证会清空'
                               {...init('company_name', {
                                   rules: [
                                       {required: true,  message: '公司名称不能为空'},
                                   ],
                               })} />
                  
                <Button type="primary" onClick={this.save.bind(this)}>保存</Button>
              </Form>
           </div>
         )
       }
  
}
ReactDOM.render(<Test />, document.getElementById('container'));

**Comment by nanjixiong218** [comment]
如果用了field做表单数据管理，就不需要设置value和onChange来进行受控了。field帮你做了这件事情来进行数据的双向绑定和管理。如果要设置初始值，在init中设置initValue即可。
参考： http://qnui.taobao.org/docs/field/?type=Field  field使用说明
