### ISSUE TITLE
有没有CDN方式的引用路径

### ISSUE THREAD

**Issue by oujiangyun** [INTL-Alibaba/qnui#4]
看了一下文档，都是NPM方式，有没有CDN的引用方式呢？文档在哪里找呢？

**Comment by fattydevelop** [comment]
cdn的版本发布与npm包版本一致，如在npm上存在0.2.0版本的qnui，则也存在`//g.alicdn.com/qn/QNUI-OPEN//0.2.0/qnui.min.js`的cdn资源。
- 推荐使用cdn引用css文件的方式，npm按需引用js文件，能够有效减少打包大小。
- 如果大范围的使用了qnui内部组件可以全部使用cdn
