### ISSUE TITLE
缺少Upload模块

### ISSUE THREAD

**Issue by YouzheJ** [INTL-Alibaba/qnui#41]
版本号：0.5.1
npm：4.1.2

import Upload模块提示undefined，然后我去node_modules中查找qnui的包，发现在lib目录下缺少了upload模块；
然后我在尝试使用fie-toolkit-qnui，发现同样为undefined，是我打开的方式不对吗？

**Comment by fattydevelop** [comment]
抱歉，文档未及时更新。

upload模块在0.5.1版本中已去除，请自行实现
