### ISSUE TITLE
日期组件示例里引用路径有错误

### ISSUE THREAD

**Issue by oujiangyun** [INTL-Alibaba/qnui#5]
发生问题的环境是：

qnui 0.1.8

qnui 版本:
qnui 0.1.8

引入了 DatePicker组件

您期待的结果是:

像官网一样正常显示

实际上的结果是:  无法引用

文档里的示例是：import DatePicker from 'qnui/lib/date-picker';

实际应该是  import DatePicker from 'qnui/lib/datepicker';

**Comment by fattydevelop** [comment]
thanks   这里的问题是同步文档时对驼峰的处理错误，下一次版本发布会修复此问题。
- 其他链接符的引用可能都需要修改为驼峰引用(待验证)。

**Comment by fattydevelop** [comment]
已在0.1.10版本修复，引用方式与文档一致
