### ISSUE TITLE
组件size统一的问题

### ISSUE THREAD

**Issue by laoxing88** [INTL-Alibaba/qnui#6]
为了各组件组合时，效果更佳。

建议在规范的时候，能够将size进行统一化处理

     比如：
     pc端size为small
     input高是24px，button和select的高是20px

**Comment by fattydevelop** [comment]
是希望同样size命名的组件的物理像素一致的吗？  

- 这个尺寸的大小都是由设计师定义且满足设计规范。

- 即使统一，恐怕small/large这种命名也只能涵盖一少部分组件。

**Comment by laoxing88** [comment]
至少同一行出现input和select的可能性极大。

>目前QNUI提供的size：

|   | small | medium | large
| ---- | ---- | ---- | ---- |
| input | 24px | 28px | 32px |
| select | 20px | 28px | 40px |

很难直接引用进行组合。

**Comment by fattydevelop** [comment]
select input组件size的问题已反馈给设计师，下一个break change版本会修复该问题
