### ISSUE TITLE
loading组件实现的js部分源码能够提供

### ISSUE THREAD

**Issue by laoxing88** [INTL-Alibaba/qnui#7]
描述
-------------------------

因为react改造需要一个过程，前期打算先直接从css和动画效果上来满足QNUI审核。

但是组件中部分js实现的代码是混淆的，没法做成完全一致，是否能提供源码或者支持？

       比如：
       loading组件

**Comment by fattydevelop** [comment]
不建议从只改UI的方式满足审核。
- 组件数量比较多，且会跟随业务动态增加，改UI是一项比较庞大的工程。
- QNUI组件专有团队维护，会定时完成bug修复和响应用户问题。
- 单单从前端来讲，接入前端MV*框架的效率提升很明显。
