### ISSUE TITLE
一部分组件没有考虑PC旺旺端的实现

### ISSUE THREAD

**Issue by laoxing88** [INTL-Alibaba/qnui#8]
描述：
--------------------------------

尤为明显的就是DatePicker，没有提供size小一点的，旺旺端很难引用

希望提的需求，你们能从使用者角度考量后再回复。

比如：https://github.com/INTL-Alibaba/qnui/issues/7

我们知道只改UI不是好办法，但是对于功能页较多的应用，短期内做react改造是有难度的，千牛平台运营是等不了的，也建议我们可以前期不走react。

作为组件支持方，希望能给予isv更多支持，谢谢~~

**Comment by fattydevelop** [comment]
qnui的侧重点在于千牛端，旺旺端暂未考虑。
